spring.application.name=ms-backend
spring.datasource.url=jdbc:postgresql://postgres:5432/srm
spring.datasource.driver-class-name=org.postgresql.Driver
spring.datasource.username=srm
spring.datasource.password=srm
spring.jpa.hibernate.ddl-auto=create-drop
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.properties.hibernate.show_sql=false
spring.jpa.open-in-view=false
SPRING_SECURITY_OAUTH2_RESOURCESERVER_JWT_ISSUER_URI: http://keycloak:8080/realms/srm-credit-engine
